apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: xmai-manager
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306

---

kind: Endpoints
apiVersion: v1
metadata:
  namespace: xmai-manager
  name: db
subsets:
- addresses:
  - ip: 192.168.1.105
  ports:
  - port: 3306