apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: xmai-manager
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379

---

kind: Endpoints
apiVersion: v1
metadata:
  namespace: xmai-manager
  name: redis
subsets:
- addresses:
  - ip: 192.168.1.110
  ports:
  - port: 6379