apiVersion: v1
kind: Service
metadata:
  name: result-server
  namespace: xmai-manager
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80

---

kind: Endpoints
apiVersion: v1
metadata:
  namespace: xmai-manager
  name: result-server
subsets:
- addresses:
  - ip: 192.168.1.106
  ports:
  - port: 80